### ISSUE TITLE
mDNS discovery not closing

### ISSUE THREAD

**Issue by iRayanKhan** [apexad/homebridge-airport-express-playing#13]
# Log:

```json
[01/08/2021, 21:54:19] Registering platform 'homebridge-airport-express-playing.AirportExpressPlaying'
[01/08/2021, 21:54:20] [Airport Express Playing Platform] Loaded homebridge-airport-express-playing v2.0.1 child bridge successfully
[01/08/2021, 21:54:20] Loaded 1 cached accessories from cachedAccessories.0E0951FA86B1.
[01/08/2021, 21:54:20] [Airport Express Playing Platform] Loading accessory from cache: Bathroom
Preparing Advertiser for 'Airport Express Playing Platform F2BD' using bonjour-hap backend!
Error: listen EADDRINUSE: address already in use :::30292
    at Server.setupListenHandle [as _listen2] (net.js:1318:16)
    at listenInCluster (net.js:1366:12)
    at Server.listen (net.js:1452:7)
    at EventedHTTPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:155:20)
    at HAPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:316:21)
    at Bridge.Accessory.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1231:18)
    at BridgeService.publishBridge (/usr/local/lib/node_modules/homebridge/src/bridgeService.ts:213:17)
    at ChildBridgeFork.startBridge (/usr/local/lib/node_modules/homebridge/src/childBridgeFork.ts:172:24)
[01/08/2021, 21:54:21] [Airport Express Playing Platform] Child bridge process ended
[01/08/2021, 21:54:21] [Airport Express Playing Platform] Process Ended. Code: 1, Signal: null
[01/08/2021, 21:54:28] [Airport Express Playing Platform] Restarting Process...
Initializing HAP-NodeJS v0.9.4...
[01/08/2021, 21:54:32] [Airport Express Playing Platform] Launched child bridge with PID 18769
[01/08/2021, 21:54:32] Registering platform 'homebridge-airport-express-playing.AirportExpressPlaying'
[01/08/2021, 21:54:32] [Airport Express Playing Platform] Loaded homebridge-airport-express-playing v2.0.1 child bridge successfully
[01/08/2021, 21:54:32] Loaded 1 cached accessories from cachedAccessories.0E0951FA86B1.
[01/08/2021, 21:54:32] [Airport Express Playing Platform] Loading accessory from cache: Bathroom
Preparing Advertiser for 'Airport Express Playing Platform F2BD' using bonjour-hap backend!
Error: listen EADDRINUSE: address already in use :::30292
    at Server.setupListenHandle [as _listen2] (net.js:1318:16)
    at listenInCluster (net.js:1366:12)
    at Server.listen (net.js:1452:7)
    at EventedHTTPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:155:20)
    at HAPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:316:21)
    at Bridge.Accessory.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1231:18)
    at BridgeService.publishBridge (/usr/local/lib/node_modules/homebridge/src/bridgeService.ts:213:17)
    at ChildBridgeFork.startBridge (/usr/local/lib/node_modules/homebridge/src/childBridgeFork.ts:172:24)
[01/08/2021, 21:54:34] [Airport Express Playing Platform] Child bridge process ended
[01/08/2021, 21:54:34] [Airport Express Playing Platform] Process Ended. Code: 1, Signal: null
[01/08/2021, 21:54:41] [Airport Express Playing Platform] Restarting Process...
```

**Comment by apexad** [comment]
The close/stop should be happening here: https://github.com/apexad/homebridge-airport-express-playing/blob/master/src/platform.ts#L80
However, since this is in a setTimeout it is outside of the natural flow and it's possible it is not always run when it should be.

**Comment by apexad** [comment]
*This package is deprecated, please use https://github.com/maxileith/homebridge-airport-express-connected (https://www.npmjs.com/package/homebridge-airport-express-connected) instead
