### ISSUE TITLE
Crashing Homebridge

### ISSUE THREAD

**Issue by ultrathew** [apexad/homebridge-airport-express-playing#7]
I'm continually getting the following in my logs just before it crashes Homebridge and restarts:

> [08/01/2021, 11:59:30] TypeError: Cannot read property 'find' of undefined
>     at Browser.<anonymous> (/usr/local/lib/node_modules/homebridge-airport-express-playing/src/platformAccessory.ts:73:42)
>     at Browser.emit (events.js:315:20)
>     at Browser.onMessage (/usr/local/lib/node_modules/homebridge-airport-express-playing/node_modules/mdns-js/lib/browser.js:128:14)
>     at module.exports.emit (events.js:315:20)
>     at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge-airport-express-playing/node_modules/mdns-js/lib/networking.js:144:10)
>     at Socket.emit (events.js:315:20)
>     at UDP.onMessage (dgram.js:919:8)
> ERROR: uncaughtException: Cannot read property 'find' of undefined
> TypeError: Cannot read property 'find' of undefined
>     at Browser.<anonymous> (/usr/local/lib/node_modules/homebridge-airport-express-playing/src/platformAccessory.ts:73:42)
>     at Browser.emit (events.js:315:20)
>     at Browser.onMessage (/usr/local/lib/node_modules/homebridge-airport-express-playing/node_modules/mdns-js/lib/browser.js:128:14)
>     at module.exports.emit (events.js:315:20)
>     at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge-airport-express-playing/node_modules/mdns-js/lib/networking.js:144:10)
>     at Socket.emit (events.js:315:20)
>     at UDP.onMessage (dgram.js:919:8)
> [08/01/2021, 11:59:30] Got SIGTERM, shutting down Homebridge...

**Comment by ultrathew** [comment]
After re-installing and trying to rule out conflicts with any other plugins, I'm now getting the following messages every time Homebridge crashes and restarts:

[10/01/2021, 11:11:23] [Living Room] INFO - shutdown
[10/01/2021, 11:11:23] ERR_SERVER_CLOSED: Cannot send packets on a closed mdns server!
    at MDNSServer.assertBeforeSend (/usr/local/lib/node_modules/homebridge/node_modules/@homebridge/ciao/src/MDNSServer.ts:403:13)
    at MDNSServer.sendOnAllNetworksForService (/usr/local/lib/node_modules/homebridge/node_modules/@homebridge/ciao/src/MDNSServer.ts:302:10)
    at MDNSServer.sendQueryBroadcast (/usr/local/lib/node_modules/homebridge/node_modules/@homebridge/ciao/src/MDNSServer.ts:263:26)
    at Prober.sendProbeRequest (/usr/local/lib/node_modules/homebridge/node_modules/@homebridge/ciao/src/responder/Prober.ts:165:17)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
ERROR: uncaughtException: Cannot send packets on a closed mdns server!
ERR_SERVER_CLOSED: Cannot send packets on a closed mdns server!
    at MDNSServer.assertBeforeSend (/usr/local/lib/node_modules/homebridge/node_modules/@homebridge/ciao/src/MDNSServer.ts:403:13)
    at MDNSServer.sendOnAllNetworksForService (/usr/local/lib/node_modules/homebridge/node_modules/@homebridge/ciao/src/MDNSServer.ts:302:10)
    at MDNSServer.sendQueryBroadcast (/usr/local/lib/node_modules/homebridge/node_modules/@homebridge/ciao/src/MDNSServer.ts:263:26)
    at Prober.sendProbeRequest (/usr/local/lib/node_modules/homebridge/node_modules/@homebridge/ciao/src/responder/Prober.ts:165:17)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
